server:
  port: 80

spring:
  application:
    name: customer-provider-80
  profiles:
    active: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource


# mybatis 配置
mybatis:
  mapper-locations: classpath*:mapper/**.xml
  type-aliases-package: com.slf.cloud.customer.provider.model